export const ADD_REMINDER = 'ADD_REMINDER_MASTER';
export const EDIT_REMINDER = 'EDIT_REMINDER_MASTER';
export const DELETE_REMINDER = 'DELETE_REMINDER_MASTER';

export const ADD_REMINDER_ACTIVITY = 'ADD_REMINDER_ACTIVITY';
export const EDIT_REMINDER_ACTIVITY = 'EDIT_REMINDER_MASTER_ACTIVITY';
export const DELETE_REMINDER_ACTIVITY = 'DELETE_REMINDER_MASTER_ACTIVITY';
export const DELETE_REMINDER_ACTIVITY_MORE = 'DELETE_REMINDER_ACTIVITY_MORE';
